"""spryx-di: Lightweight type-based dependency injection for Python modular monoliths."""

from spryx_di.container import Container, ScopedContainer
from spryx_di.errors import (
    AmbiguousExportError,
    CircularDependencyError,
    CircularDependencyInModulesError,
    CircularImportError,
    InvalidListenerError,
    MissingEventBackendError,
    ModuleBoundaryError,
    PublicAccessError,
    SerializationError,
    SpryxDIError,
    TypeHintRequiredError,
    UnresolvableTypeError,
    UnresolvedDependencyError,
    UnresolvedImportError,
)
from spryx_di.events import (
    AsyncEventBackend,
    EventBus,
    EventHandler,
    EventListener,
    EventMetadata,
    ListenerScope,
)
from spryx_di.module import ApplicationContext, Module
from spryx_di.provider import (
    ClassProvider,
    ExistingProvider,
    FactoryProvider,
    Provider,
    Scope,
    ValueProvider,
    public,
)

__all__ = [
    "AmbiguousExportError",
    "ApplicationContext",
    "AsyncEventBackend",
    "CircularDependencyError",
    "CircularDependencyInModulesError",
    "CircularImportError",
    "ClassProvider",
    "Container",
    "EventBus",
    "EventHandler",
    "EventListener",
    "EventMetadata",
    "ExistingProvider",
    "FactoryProvider",
    "InvalidListenerError",
    "ListenerScope",
    "MissingEventBackendError",
    "Module",
    "ModuleBoundaryError",
    "PublicAccessError",
    "Provider",
    "ScopedContainer",
    "Scope",
    "SerializationError",
    "SpryxDIError",
    "TypeHintRequiredError",
    "UnresolvedDependencyError",
    "UnresolvedImportError",
    "UnresolvableTypeError",
    "ValueProvider",
    "public",
]
